// 皮肤主题定义
const SKINS = {
  sakura: {
    name: '樱花',
    bg: '#fff5f8',
    bgAlt: '#fff0f5',
    primary: '#ff69b4',
    primaryLight: '#ff99cc',
    primaryDark: '#c2185b',
    border: '#ffd6e5',
    textMuted: '#c8a0b0',
    surface: '#ffe4ec',
  },
  ocean: {
    name: '海洋',
    bg: '#f0f8ff',
    bgAlt: '#e8f4fd',
    primary: '#4a9fd5',
    primaryLight: '#7bbce6',
    primaryDark: '#1a5276',
    border: '#c5dff0',
    textMuted: '#8badc4',
    surface: '#d4eaf7',
  },
  lavender: {
    name: '薰衣草',
    bg: '#f8f0ff',
    bgAlt: '#f3e8ff',
    primary: '#9b59b6',
    primaryLight: '#bb8fce',
    primaryDark: '#6c3483',
    border: '#d7bde2',
    textMuted: '#b0a0c0',
    surface: '#e8d5f5',
  },
  mint: {
    name: '薄荷',
    bg: '#f0fff8',
    bgAlt: '#e8fdf3',
    primary: '#27ae60',
    primaryLight: '#58d68d',
    primaryDark: '#1e8449',
    border: '#c5f0d6',
    textMuted: '#8bc4a0',
    surface: '#d5f5e3',
  },
  peach: {
    name: '蜜桃',
    bg: '#fff8f0',
    bgAlt: '#fef3e8',
    primary: '#e67e22',
    primaryLight: '#f0a858',
    primaryDark: '#a04000',
    border: '#f5dfc5',
    textMuted: '#c4a888',
    surface: '#fde8d0',
  },
  starry: {
    name: '星空',
    bg: '#f0f0ff',
    bgAlt: '#e8e8fd',
    primary: '#5b6abf',
    primaryLight: '#8890d5',
    primaryDark: '#2c3e7a',
    border: '#c5c8f0',
    textMuted: '#9898c0',
    surface: '#d5d8f5',
  },
};
